### ISSUE TITLE
How to gather images url

### ISSUE THREAD

**Issue by lukezona** [wpmovielibrary/wpmovielibrary#271] opened 2015-05-26 13:47 UTC
Hi, I'm looking for a way to use movie's images as a div background..

I would like to make something like the movie-modal in the admin dashboard but I can't gather the images url.. 

How can I do that?

Luca

**Comment by CaerCam** [comment] 2015-05-29 13:30
Duplicate of #268, I'll answer there ;)

**Closed by CaerCam** 2015-05-29 13:30 UTC
