### ISSUE TITLE
movie_gird orderby does not work

### ISSUE THREAD

**Issue by zocoloco** [wpmovielibrary/wpmovielibrary#243] opened 2015-03-15 07:10 UTC
I'm trying to order the movie grid by post date. when I use orderby="date", it doesn't work. I see that the attribute exists in wpmoly-shortcodes.php (both order and orderby), but returns no results if used in the shortcode.

**Comment by CaerCam** [comment] 2015-03-15 11:59
No way I can find what's going wrong without any more details. I'll think about a way to log important data when WP_DEBUG in on, so we can work on this effectively.

**Comment by CaerCam** [comment] 2015-03-15 12:00
Note: possible duplicate of #242, BTW.

**Comment by zocoloco** [comment] 2015-03-15 18:23
I figured it out. I'm using WPMovieLibrary for movie reviews. So the order needs to be by post_date. In class-wpmoly-grid.php I changed line 298 from:
 } else {
 to  
} elseif ($orderby == '' ) { // no value in shortcode args

so that it only changes the order by value to "post_title" if there no orderby value in the shortcode args.

You might also want to include post_date in wpmoly_shortcodes.php array value, although it wouldn't be necessary if coded like above (accepting any value).

Could you change this if the next update?

Great plugin! Your coding is outstanding. Thanks!

**Comment by CaerCam** [comment] 2015-03-16 11:13
Ok, I didn't get you were looking for _post_date_, which isn't supported yet.

**Closed** 2015-04-04 06:56 UTC
Labels: bug
