### ISSUE TITLE
Own Trailer Link

### ISSUE THREAD

**Issue by stargatehome** [wpmovielibrary/wpmovielibrary#252] opened 2015-04-05 09:34 UTC
Hey Charlie,

is it in the actual version possible to add you own link to trailer. Would be great. ;)

Cheers,
Mario

PS: Open the plugin to editors would really help, so it can be better used. ;)

**Comment by CaerCam** [comment] 2015-04-05 16:18
Yup, that's been requested a few times already. That's related to the Trailers plugins, though, not main plugin; it will be possible at some point, it's just not a priority right now due to the overload of work I have, on WPMovieLibrary as well as in my own work :(

PS: do you mean editors like "WordPress editor role"?

**Comment by stargatehome** [comment] 2015-04-05 16:51
Hey, 

yeah I mean the WordPress Editor. I've tested it and he cannot use the plugin. :/ Would be great, if he could. ;)

Cheers

**Comment by CaerCam** [comment] 2015-04-05 16:54
Ok, probable duplicate of #80 then?

**Comment by stargatehome** [comment] 2015-04-06 10:22
Yeah, I wanted to "push" it in a way, because, that is in fact the importest feature, I recommended, because, at that point the plugin would be work for a editing and that's great. There mustn't be tons of options to handle this access, a simple can use and can not use, would make the life easier. :)

**Comment by CaerCam** [comment] 2015-04-07 07:49
Actually it's more complex than it looks. I mean, I could probably make it easier to change using a filter, you would then need to add a couple of lines to your theme's `functions.php` to change the role needed to edit movies − maybe I'll do something likely, now that I threw the idea − but it will be a very limited view of what I plan for #80.

The idea behind the role and capabilities enhancement is to have real permissions and capabilities, for instance allow editors or contributors to change specific details but not metadata, change taxonomies but not details, update metadata but not create new movies, etc. This will require a lot of work, too, first to sort out what should or shouldn't be subject to permissions, and then unify the final role/cap scheme to be easily controllable by the Settings panel as well as other plugins/tools (Adminimize first comes to mind, but that not the only one).

This kind of − rather heavy − features are what I plan to work on when version 2.2 is out. 2.2 is my primary goal right now: the plugin is getting popular and still have a crappy admin side with a lot of weaknesses and lack of features; it really needs to be handled first thing. Improving the frontend grid is the second priority as it causes too many issues and is to limited the way it's currently built, whereas permissions have a limited impact as in most cases, the plugin is only used by one person who has the highest permissions and is not limited.

**Comment by stargatehome** [comment] 2015-04-07 11:14
OK. ;)

**Closed** 2016-04-17 09:54 UTC
Labels: deprecated, question
